name: Build

on:
  workflow_call:
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Install ziglang for cross-compilation
        run: |
          wget https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz
          tar xf zig-linux-x86_64-0.13.0.tar.xz
          echo "$(pwd)/zig-linux-x86_64-0.13.0" >> $GITHUB_PATH

      - name: Install cargo-zigbuild
        run: cargo install cargo-zigbuild

      - name: Build for ${{ matrix.target }}
        run: cargo zigbuild --target ${{ matrix.target }} --release
